### PR TITLE
add share button with native share for mobile and custom share for we…

### PR DESCRIPTION
**Pull request by danielbenedykt**
Added share library that runs navigator.share where available,  and falls back to a custom layout where is not available

Also added https plugin to allow to test navigator.share

### CODE REVIEW

**Comment by EfratGutman** [comment]
Hey sorry, for some reason I can't run this branch locally.
Until I fix this issue, could you please add a short video of how its going to be looked like?

**Comment by danielbenedykt** [comment]
> Hey sorry, for some reason I can't run this branch locally. Until I fix this issue, could you please add a short video of how its going to be looked like?

What issue are you having ?
to run it make sure you run 
npm install
and then use https and your computer IP from your phone to test

image

**Comment by EfratGutman** [comment]
Yes I have an issue with the 'node' version

**Comment by danielbenedykt** [comment]
https://github.com/CalculatorMiluim/Calculator-Miluim/assets/307628/7845765b-86ea-4a1c-8732-228774f2128d

@EfratGutman

**Review by EfratGutman — APPROVED** [review]

**Pull request merged**
